###
POST http://localhost:5000 HTTP/1.1
Content-Type : application/json

{
    "Name" : "Venkata Gagan Gamya"
}

###
POST http://localhost:5000 HTTP/1.1
Content-Type : application/json

{
    "fileID" : "03",
    "employess":[
        {
            "name":"First",
            "role":"Admin"
        },
        {
            "name":"Second",
            "role":"Developer"
        }
    ]
}

###
GET http://localhost:5000/localProdJSON

###
GET http://localhost:5000/getNorthwindsrv/

###
GET http://localhost:5000/getNorthwindsrvAsync/

###
GET http://localhost:5000/getNorthwindFilters/SupplierID=2

###
GET http://localhost:5000/api/localProducts/

###
GET http://localhost:5000/api/nwProducts
###
POST http://localhost:5000/localProdJSON
Content-Type : application/json

{
      "ProductID": 21,
      "ProductName": "Teatime Chocolate Biscuits",
      "SupplierID": 8,
      "CategoryID": 3,
      "QuantityPerUnit": "10 boxes x 12 pieces",
      "UnitPrice": 9.2,
      "UnitsInStock": 25,
      "UnitsOnOrder": 0,
      "ReorderLevel": 5,
      "Discontinued": false
    }

